# Generated by Django 3.0.1 on 2020-08-16 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200816_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form1model',
            old_name='Quantity',
            new_name='quantity',
        ),
    ]
