# Generated by Django 3.0.1 on 2020-08-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200816_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form1model',
            name='quantity',
            field=models.IntegerField(blank=True),
        ),
    ]
