# Generated by Django 3.0.1 on 2020-08-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200816_1654'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Form2model',
        ),
        migrations.RenameField(
            model_name='form1model',
            old_name='input_waste',
            new_name='num_trips',
        ),
        migrations.RemoveField(
            model_name='form1model',
            name='output_waste',
        ),
        migrations.AddField(
            model_name='form1model',
            name='comments',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='form1model',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='form1model',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='form1model',
            name='type_waste',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='form1model',
            name='vehicle_number',
            field=models.CharField(default=5, max_length=50),
            preserve_default=False,
        ),
    ]
