# Generated by Django 3.0.1 on 2020-08-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200816_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form1model',
            name='location',
            field=models.CharField(choices=[('delhi', 'DELHI'), ('kolkata', 'KOLKATA'), ('mumbai', 'MUMBAI'), ('trichy', 'TRICHY')], max_length=50),
        ),
    ]
